spring:
  application:
    name: consumer  # Name of the Spring Boot application
  cloud:
    stream:
      function:
        definition: processEmployeeData
      bindings:
        processEmployeeData-in-0:
          destination: my-new-topic
          group: employee-data-group  # In case of multiple instances group will ignore the multiple times reading of same message
    kafka:
      binder:
        brokers: localhost:9092

server:
  port: 8081  # Port on which the application will run
