spring:
  application:
    name: producer  # Unique name for this Spring Boot application instance

  cloud:
    function:
      definition: sendEmployeeDetails  # Name of the function bean to expose as a messaging function

    stream:
      function:
        definition: sendEmployeeDetails  # Links the stream configuration to the specific function

      bindings:
        sendEmployeeDetails-out-0:  # Output binding (index 0) for the function 'sendEmployeeDetails'
          destination: my-topic  # Kafka topic name where the messages will be sent
          content-type: application/json  # Message content type (serialized as JSON)

      poller:
        fixed-delay: 5000  # Time interval (in ms) between each poll for Supplier functions (5 seconds here)

      kafka:
        binder:
          brokers: localhost:9092  # Kafka broker address; change to your Kafka server if running elsewhere